version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: etech_store_postgres
    environment:
      POSTGRES_DB: etech_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0788299605
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
