ALTER TABLE payments
    DROP CONSTRAINT fk_payments_on_order;

ALTER TABLE review
    DROP CONSTRAINT fk_review_on_product;

ALTER TABLE review
    DROP CONSTRAINT fk_review_on_user;

CREATE TABLE order_payments
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id             VARCHAR(255)                            NOT NULL,
    momo_reference_id    VARCHAR(255),
    external_id          VARCHAR(255),
    amount               DECIMAL(12, 2)                          NOT NULL,
    currency             VARCHAR(255)                            NOT NULL,
    customer_phone       VARCHAR(255)                            NOT NULL,
    customer_name        VARCHAR(255)                            NOT NULL,
    customer_email       VARCHAR(255),
    payment_description  VARCHAR(255),
    order_items          TEXT,
    payment_status       VARCHAR(255)                            NOT NULL,
    momo_transaction_id  VARCHAR(255),
    error_reason         VARCHAR(255),
    payment_initiated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    payment_completed_at TIMESTAMP WITHOUT TIME ZONE,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_order_payments PRIMARY KEY (id)
);

CREATE TABLE payment
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    payment_type     VARCHAR(31),
    order_id         BIGINT,
    amount           DECIMAL,
    currency         VARCHAR(255),
    method           VARCHAR(255),
    status           VARCHAR(255),
    payment_date     TIMESTAMP WITHOUT TIME ZONE,
    transaction_id   VARCHAR(255),
    card_number      VARCHAR(255),
    card_holder_name VARCHAR(255),
    expiry_date      VARCHAR(255),
    cvv              VARCHAR(255),
    billing_address  VARCHAR(255),
    phone_number     VARCHAR(255),
    rwanda_id_number VARCHAR(255),
    CONSTRAINT pk_payment PRIMARY KEY (id)
);

CREATE TABLE product_images
(
    product_id BIGINT NOT NULL,
    image_url  VARCHAR(512)
);

CREATE TABLE review_comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content    VARCHAR(1000)                           NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    review_id  BIGINT,
    user_id    BIGINT,
    CONSTRAINT pk_review_comments PRIMARY KEY (id)
);

CREATE TABLE reviews
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content    VARCHAR(2000)                           NOT NULL,
    rating     INTEGER                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    product_id BIGINT,
    user_id    BIGINT,
    CONSTRAINT pk_reviews PRIMARY KEY (id)
);

ALTER TABLE users
    ADD account_non_expired BOOLEAN;

ALTER TABLE users
    ADD account_non_locked BOOLEAN;

ALTER TABLE users
    ADD credentials_non_expired BOOLEAN;

ALTER TABLE users
    ADD description TEXT;

ALTER TABLE users
    ADD enabled BOOLEAN;

ALTER TABLE users
    ADD first_name VARCHAR(50);

ALTER TABLE users
    ADD last_name VARCHAR(50);

ALTER TABLE users
    ADD phone_number VARCHAR(255);

ALTER TABLE users
    ADD profile_picture_url VARCHAR(255);

ALTER TABLE users
    ALTER COLUMN account_non_expired SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN account_non_locked SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN credentials_non_expired SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN enabled SET NOT NULL;

ALTER TABLE products
    ADD image_urls VARCHAR(255);

ALTER TABLE products
    ADD main_image VARCHAR(512);

ALTER TABLE products
    ADD main_image_url VARCHAR(255);

ALTER TABLE orders
    ADD rwanda_phone_number VARCHAR(255);

ALTER TABLE orders
    ADD rwanda_tax_code VARCHAR(255);

ALTER TABLE wishlists
    ADD share_token VARCHAR(255);

ALTER TABLE wishlists
    ADD share_token_expiry TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE categories
    ADD slug VARCHAR(100);

ALTER TABLE reviews
    ADD CONSTRAINT uc_dfde71e504b15345708ce7e55 UNIQUE (product_id, user_id);

ALTER TABLE order_payments
    ADD CONSTRAINT uc_order_payments_external UNIQUE (external_id);

ALTER TABLE order_payments
    ADD CONSTRAINT uc_order_payments_momo_reference UNIQUE (momo_reference_id);

ALTER TABLE order_payments
    ADD CONSTRAINT uc_order_payments_order UNIQUE (order_id);

ALTER TABLE payment
    ADD CONSTRAINT uc_payment_order UNIQUE (order_id);

ALTER TABLE payment
    ADD CONSTRAINT FK_PAYMENT_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE review_comments
    ADD CONSTRAINT FK_REVIEW_COMMENTS_ON_REVIEW FOREIGN KEY (review_id) REFERENCES reviews (id);

ALTER TABLE review_comments
    ADD CONSTRAINT FK_REVIEW_COMMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE product_images
    ADD CONSTRAINT fk_product_images_on_product FOREIGN KEY (product_id) REFERENCES products (id);

DROP TABLE contact_message CASCADE;

DROP TABLE payments CASCADE;

DROP TABLE review CASCADE;

ALTER TABLE orders
    DROP COLUMN order_number;

ALTER TABLE orders
    ALTER COLUMN address_id DROP NOT NULL;

ALTER TABLE orders
    ALTER COLUMN order_date DROP NOT NULL;

ALTER TABLE orders
    ALTER COLUMN shipping_fee TYPE DECIMAL USING (shipping_fee::DECIMAL);

ALTER TABLE orders
    ALTER COLUMN shipping_fee DROP NOT NULL;

ALTER TABLE orders
    ALTER COLUMN status TYPE VARCHAR(255) USING (status::VARCHAR(255));

ALTER TABLE orders
    ALTER COLUMN status DROP NOT NULL;

ALTER TABLE orders
    ALTER COLUMN subtotal TYPE DECIMAL USING (subtotal::DECIMAL);

ALTER TABLE orders
    ALTER COLUMN subtotal DROP NOT NULL;

ALTER TABLE orders
    ALTER COLUMN tax TYPE DECIMAL USING (tax::DECIMAL);

ALTER TABLE orders
    ALTER COLUMN tax DROP NOT NULL;

ALTER TABLE orders
    ALTER COLUMN total TYPE DECIMAL USING (total::DECIMAL);

ALTER TABLE orders
    ALTER COLUMN total DROP NOT NULL;

ALTER TABLE orders
    ALTER COLUMN user_id DROP NOT NULL;