# ========================
# Application Info
# ========================
spring:
  application:
    name: e_tech_store_app
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/e_tech_store_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

app:
  api:
    version: v1
  payment:
    base-currency: USD
    allowed-currencies: USD,RWF,EUR,GBP

# PayPal Configuration
paypal:
  client-id: ${paypal.client-id}
  client-secret: ${paypal.client-secret}
  mode: sandbox # or live for production
#  return-url: http://localhost:8080/api/v1/payments/paypal/return
#  cancel-url: http://localhost:8080/api/v1/payments/paypal/cancel

# MTN Mobile Money Configuration
mtn:
  mobile-money:
    api-key: your-mtn-api-key
    merchant-id: your-merchant-id
    callback-url: http://localhost:8080/api/v1/payments/mtn/callback
    currency: RWF
    countries: RW

# Security Configuration
security:
  jwt:
    secret: your-jwt-secret-key
    expiration-ms: 86400000 # 24 hours