spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/etech_store
    password: 0788299605
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

        # For application.yml
        spring:
          flyway:
            baseline-on-migrate: true
            baseline-version: 1