CREATE TABLE order_payments
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id             VARCHAR(255)                            NOT NULL,
    momo_reference_id    VARCHAR(255),
    external_id          VARCHAR(255),
    amount               DECIMAL(12, 2)                          NOT NULL,
    currency             VARCHAR(255)                            NOT NULL,
    customer_phone       VARCHAR(255)                            NOT NULL,
    customer_name        VARCHAR(255)                            NOT NULL,
    customer_email       VARCHAR(255),
    payment_description  VARCHAR(255),
    order_items          TEXT,
    payment_status       VARCHAR(255)                            NOT NULL,
    momo_transaction_id  VARCHAR(255),
    error_reason         VARCHAR(255),
    payment_initiated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    payment_completed_at TIMESTAMP WITHOUT TIME ZONE,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_order_payments PRIMARY KEY (id)
);

ALTER TABLE users
    ADD account_non_expired BOOLEAN;

ALTER TABLE users
    ADD account_non_locked BOOLEAN;

ALTER TABLE users
    ADD credentials_non_expired BOOLEAN;

ALTER TABLE users
    ADD enabled BOOLEAN;

ALTER TABLE users
    ALTER COLUMN account_non_expired SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN account_non_locked SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN credentials_non_expired SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN enabled SET NOT NULL;

ALTER TABLE order_payments
    ADD CONSTRAINT uc_order_payments_external UNIQUE (external_id);

ALTER TABLE order_payments
    ADD CONSTRAINT uc_order_payments_momo_reference UNIQUE (momo_reference_id);

ALTER TABLE order_payments
    ADD CONSTRAINT uc_order_payments_order UNIQUE (order_id);

ALTER TABLE orders
DROP
COLUMN order_number;

ALTER TABLE orders
    ALTER COLUMN address_id DROP NOT NULL;

ALTER TABLE payment
ALTER
COLUMN amount TYPE DECIMAL USING (amount::DECIMAL);

ALTER TABLE orders
    ALTER COLUMN order_date DROP NOT NULL;

ALTER TABLE payment
    ALTER COLUMN payment_type DROP NOT NULL;

ALTER TABLE order_items
ALTER
COLUMN price_at_purchase TYPE DECIMAL USING (price_at_purchase::DECIMAL);

ALTER TABLE orders
ALTER
COLUMN shipping_fee TYPE DECIMAL USING (shipping_fee::DECIMAL);

ALTER TABLE orders
    ALTER COLUMN shipping_fee DROP NOT NULL;

ALTER TABLE orders
    ALTER COLUMN status DROP NOT NULL;

ALTER TABLE orders
ALTER
COLUMN subtotal TYPE DECIMAL USING (subtotal::DECIMAL);

ALTER TABLE orders
    ALTER COLUMN subtotal DROP NOT NULL;

ALTER TABLE orders
ALTER
COLUMN tax TYPE DECIMAL USING (tax::DECIMAL);

ALTER TABLE orders
    ALTER COLUMN tax DROP NOT NULL;

ALTER TABLE orders
ALTER
COLUMN total TYPE DECIMAL USING (total::DECIMAL);

ALTER TABLE orders
    ALTER COLUMN total DROP NOT NULL;

ALTER TABLE shopping_carts
ALTER
COLUMN total_price TYPE DECIMAL USING (total_price::DECIMAL);

ALTER TABLE orders
    ALTER COLUMN user_id DROP NOT NULL;